{
    'name': 'Project Shop',
    'category': 'vuhai',
    'author': 'vuhai',
    'description': 'Customize Product',
    'depends': [
        'sale',
        'stock_account',
        # 'users_inherit',
        'point_of_sale',
        'purchase',
        'pos_promotion',
    ],
    'data': [
        'data/update_stock_quantity.xml',
        'security/res_group.xml',
        'views/product.xml',
        'views/stock.xml',
        'views/pos.xml',
        'views/purchase_order.xml',
        'views/web_title.xml',
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'reports/stock_report_wizard.xml',
        'reports/pos_report_final_wizard.xml',
        'reports/purchase_report.xml',
        'reports/stock_report.xml',
        'reports/pos_report.xml',
        'reports/pos_reprint.xml',
        'reports/report.xml',
    ],
    'installable': True,
    'qweb':[
        'static/src/xml/base.xml',
        'static/src/xml/web.xml',
        'static/src/xml/pos.xml',
        # 'static/src/xml/web_title.xml',
    ],
    # 'css': ['static/src/css/*.css'],
}